#!/usr/bin/with-contenv bash

if [ -f /config/cron ]; then
   crontab /config/cron
fi

if [ ! -f /config/cron ]; then
   echo '10 04 * * * sudo -H -u abc /usr/local/bin/tv_grab_nl3.py -C /config/tv_grab_nl3_py.conf --output /config/xmltv.xml --disable-detail-source 3 >>/config/cron.log 2>&1
'>/config/cron
   crontab /config/cron
fi
