FROM dorowu/ubuntu-desktop-lxde-vnc:bionic

RUN \
  add-apt-repository ppa:micahflee/ppa -y && \
  apt-get --assume-yes update && \
  apt-get --assume-yes install traceroute iputils-ping wget torbrowser-launcher

  