#!/usr/bin/with-contenv bash

if [ -f /config/cron ]; then
   crontab /config/cron
fi

if [ ! -f /config/cron ]; then
   echo '* * * * *   echo "run: $(date)" >>/config/cron.log 2>&1'>/config/crontest
   crontab /config/cron
fi
