version: '2'
services:
  cacti-master:
    image: "smcline06/cacti"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DB_NAME=cacti_master
      - DB_USER=cactiuser
      - DB_PASS=cactipassword
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASS=rootpassword
      - INITIALIZE_DB=1
      - TZ=America/Los_Angeles
    links:
      - db

  cacti-poller:
    image: "smcline06/cacti"
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - DB_NAME=cacti_poller
      - DB_USER=cactipolleruser
      - DB_PASS=cactipollerpassword
      - DB_HOST=db
      - DB_PORT=3306
      - RDB_NAME=cacti_master
      - RDB_USER=cactiuser
      - RDB_PASS=cactipassword
      - RDB_HOST=db
      - RDB_PORT=3306
      - DB_ROOT_PASS=rootpassword
      - REMOTE_POLLER=1
      - INITIALIZE_DB=1
      - TZ=America/Los_Angeles
    links:
      - db

  db-master:
    image: "percona:5.7.14"
    ports:
      - "3306:3306"
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=200
      - --max_heap_table_size=128M
      - --max_allowed_packet=32M
      - --tmp_table_size=128M
      - --join_buffer_size=128M
      - --innodb_buffer_pool_size=1G
      - --innodb_doublewrite=OFF
      - --innodb_flush_log_at_timeout=3
      - --innodb_read_io_threads=32
      - --innodb_write_io_threads=16
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - TZ=America/Los_Angeles
