name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: bittorrent/go-btfs
        path: './btfs'

    - name: Modify scripts and get version
      id: version
      run: |
        output=$(date -u '+%Y%m%d%H%M%S')
        echo ::set-output name=date_version::$output

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    # here you can do additional steps

    - name: Build and push
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./btfs
        file: ./btfs/Dockerfile
        platforms: linux/arm/v7, linux/amd64
        push: true
        tags: |
          ghcr.io/${{github.repository}}:latest
          ghcr.io/${{github.repository}}:${{steps.version.outputs.date_version}}